language: python

install:
  - pip install dateparser
  - pip install tldextract
  - pip install ipython
  - pip install matplotlib

script: python -m pytest

notifications:
  email:
    recipients:
      - juho.paakkonen@helsinki.fi
      - matti.nelimarkka@aalto.fi
      - arto.kekkonen@helsinki.fi

    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://head.hiit.fi/hooks/1e7x53p1fjbqprexeohhq3tzsy
    on_success: always
    on_failure: always
